### ISSUE TITLE
Code128 issue

### ISSUE THREAD

**Issue by Jonney3099** [zint/zint-gpl-only#54]
When I test string 'c' + '\n' + "aDEF" , Code128 Class returns:
|START B|c|Shift|Chr(10)|SHIFT|a|D|E|F|CheckDigit|STOP|
There're two SHIFT,the last SHIFT is redundant. Scanner returns wrong result.

The program I tested is OkapiBarcode which is inherited from zint. I think zint also has the same hole.

**Comment by gitlost** [comment]
The latest version of Zint produces "StartB c ShA <LF> a D E F k Stop CSum(75)" (checked with ZXing-C++), i.e. without the redundant SHIFT, so it looks as if this issue is fixed. If you've any further feedback please raise a ticket at https://sourceforge.net/p/zint/tickets/ as this fork is no longer in use. Thanks for the detailed feedback!
