### ISSUE TITLE
Support for JPEG file formats

### ISSUE THREAD

**Issue by iamsumit** [zint/zint-gpl-only#76]
Currently, it generates following types of barcodes only. Can we please have support for JPEG?

![image](https://user-images.githubusercontent.com/1046307/86210137-b6380c80-bb91-11ea-9b67-89f7904ef5fc.png)

**Comment by oehhar** [comment]
Thank you for the question.
Unfortunately, jpeg is an unsuited format for barcodes as it has by design issues with sharp edges and all supported symbologies are created by a set of squares.

I recommend to use codes which are suited to the jpeg format which typically act in the low frequency domain.

In addition, this git project is not the most current. You may consider to change to zint on sourceforge.

Best regards,
Harald

**Comment by gitlost** [comment]
Hi as Harald says jpeg is unsuited to barcodes and doesn't offer any advantages over png or gif or other supported raster formats. If you've any further feedback please raise a ticket at https://sourceforge.net/p/zint/tickets/, thanks.
