### ISSUE TITLE
Suggestion: Have a setting which allows to start up with a different type of code

### ISSUE THREAD

**Issue by Joe23232** [zint/zint-gpl-only#81]
By default it is set to barcode. I wanted to suggest a setting to change the default code that it loads up, for example it the setting will allow me to load up QR code instead of barcode.

**Comment by oehhar** [comment]
If you speak about zint on sourceforge, it is implemented there. Last symbology is saved and restored at the next start.
If you speak about this unmaintained fork, you may implement it on your own.

Hope this helps,
Harald

**Comment by Joe23232** [comment]
Oh I didn't realise that, thanks :)

**Comment by Joe23232** [comment]
@oehhar 

![image](https://user-images.githubusercontent.com/34926497/105682016-015aa800-5f46-11eb-851e-389fd8525fdf.png)


Isn't there a 64bit version of Zing?

**Comment by oehhar** [comment]
I only compile the 32 bit windows version. I suppose, a 64 bit version may be build, but I will not do that.
The reason is, that a 32 bit version may be run on any computer.
zint.exe is build using ms-vc 6 (20 years old) to avoid what is called "DLL hell". So, it will run from Windows XP to WIndows 10.

**Comment by Joe23232** [comment]
Right I see mate

**Comment by gitlost** [comment]
Hi, as this issue appears to be resolved an closing it now. If you've any further feedback please raise a ticket at https://sourceforge.net/p/zint/tickets/, thanks!
