### ISSUE TITLE
Version 2.9.1 stopped creating batch outputs

### ISSUE THREAD

**Issue by germanmedinasl** [zint/zint-gpl-only#82]
I started using yesterday Zint Barcode, however, after a couple of tries, the batch generation is not working anymore, it just outputs the first code on the list. 
I'm using EAN, and tried with different files output (png, svg). Same result. 
I also got a previous error that didn't allow me to output in a specific directory, my guess is that it had a space and accented word.

**Comment by germanmedinasl** [comment]
Update: Command line has the same issue. Just the first of the file is created, in this case with a strange character at start:
ï»¿8411125079055 
(it should be just 8411125079055). Note that the file type is SVG.

**Comment by gitlost** [comment]
Hi, re the GUI issue and it previously requiring a linefeed after the last entry, this is now fixed in the latest version of ZInt. Re the command line CLI and having a strange character at the start, this is not reproducible in the current version. Am closing this as this fork is no longer in use. If you still have issues or further feedback please raise a ticket at https://sourceforge.net/p/zint/tickets/ and it will be looked at, thanks for the feedback.
