### ISSUE TITLE
Add a picture at the centre of QR code

### ISSUE THREAD

**Issue by waiwaileung** [zint/zint-gpl-only#83]
I would like to add a picture at the centre of QR code to promote our brand, however, I cannot find such command to execute for Zint, grateful for any advice.

**Comment by gitlost** [comment]
Hi this issue is duplicated at https://sourceforge.net/p/zint/tickets/240/ for which see details (no immediate plans to implement this but maybe in the future...). This fork is no longer in use so am closing this. If you've any further suggestions or feedback, please open a ticket at https://sourceforge.net/p/zint/tickets/240/, thanks.
